language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - nightly
matrix:
  allow_failures:
    - python: nightly
sudo: false
install: pip install coveralls flake8 pep257
script:
  - flake8 .
  - pep257 .
  - coverage run --source=prawcore setup.py test
after_success: coveralls
