after_success: coveralls
cache: pip
install: pip install coveralls flake8 pep257
language: python
matrix:
  allow_failures:
    - python: nightly
  fast_finish: true
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - nightly
script:
  - flake8 .
  - pep257 .
  - coverage run --source=prawcore setup.py test
sudo: false
